# Generated by Django 5.0.4 on 2024-05-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Site. Site name should be unique.', max_length=200, unique=True)),
                ('kmaster_IP_address', models.GenericIPAddressField()),
                ('knode1_IP_address', models.GenericIPAddressField()),
                ('knode2_IP_address', models.GenericIPAddressField()),
                ('username', models.CharField(help_text='This username will be used to access the servers.', max_length=50)),
                ('password', models.CharField(help_text='The password for the username. Will be used to access servers.', max_length=50)),
                ('dashboard_url', models.URLField()),
                ('is_cloud_site', models.BooleanField(help_text='True if this is a cloud site else if op prem site then False.')),
            ],
        ),
    ]
