# Generated by Django 5.0.4 on 2024-05-11 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_sitemodel_is_cloud_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='dashboard_password',
            field=models.CharField(default=django.utils.timezone.now, help_text='This password will be used to login to dashboards.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='dashboard_username',
            field=models.CharField(default=django.utils.timezone.now, help_text='This username will be used to login to dashboards.', max_length=50),
            preserve_default=False,
        ),
    ]
