# Generated by Django 5.0.4 on 2024-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_sitemodel_dashboard_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudSiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Site. Site name should be unique.', max_length=200, unique=True)),
                ('hostname', models.GenericIPAddressField()),
                ('username', models.CharField(help_text='This username will be used to access the servers.', max_length=50)),
                ('password', models.CharField(help_text='The password for the username. Will be used to access servers.', max_length=50)),
                ('dashboard_url', models.URLField()),
                ('dashboard_username', models.CharField(help_text='This username will be used to login to dashboards.', max_length=50)),
                ('dashboard_password', models.CharField(help_text='This password will be used to login to dashboards.', max_length=50)),
                ('cluster_name', models.CharField(help_text='Cluster to be switched.', max_length=50)),
                ('namespace_name', models.CharField(help_text='Namespace to be switched.', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='sitemodel',
            name='is_cloud_site',
        ),
    ]
